# Raycast script commands
[".config/raycast/_enabled-scripts-commands/epoch-to-human-date.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/epoch-to-human-date.sh"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/human-date-to-epoch.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/human-date-to-epoch.sh"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/hex-to-rgb.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/hex-to-rgb.sh"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/hex-to-rgba.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/hex-to-rgba.sh"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/images/lungo.png"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/apps/lungo/images/lungo.png"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/lungo-activate.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/apps/lungo/lungo-activate.sh"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/lungo-deactivate.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/apps/lungo/lungo-deactivate.sh"
refreshPeriod = "168h"
[".config/raycast/_enabled-scripts-commands/lungo-toggle.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/apps/lungo/lungo-toggle.sh"
refreshPeriod = "168h"
# superpowers for opencode
[".config/opencode/superpowers"]
type = "archive"
url = "https://github.com/miszo/superpowers/archive/refs/heads/main.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
# tmuxifier
[".tmuxifier"]
type = "archive"
url = "https://github.com/jimeh/tmuxifier/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = ["*/.*", "*/examples", "*/layouts"]
